#.travis.yml

language: node_js
node_js:
  - "13.5.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install codecov -g

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - codecov

notifications:
  email:
    - jkkr.1996@gmail.com
